first:
	@clang ./src/first.c -o ./bin/first
	@./bin/first

second:
	@clang ./src/second.c -o ./bin/second
	@./bin/second

third:
	@clang ./src/third.c -o ./bin/third
	@./bin/third

fourth:
	@clang ./src/fourth.c -o ./bin/fourth
	@./bin/fourth

fifth:
	@clang ./src/fifth.c -o ./bin/fifth
	@./bin/fifth